#!/bin/sh      
 cd /var/www/cs485-meeting-application/
 sudo git pull  
 cd /var/www/cs485-meeting-application/frontend 
 sudo npm install
 sudo npm run build
 cd /var/www/cs485-meeting-application/backend
 sudo npm install 
 sudo pm2 restart all
 exit      